#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJson = JSON.parse(
	readFileSync(join(__dirname, "..", "package.json"), "utf-8"),
);

const versionContent = `// Auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION = "${packageJson.version}";
`;

writeFileSync(
	join(__dirname, "..", "src", "core", "version.ts"),
	versionContent,
);

console.log(`Generated version.ts with version ${packageJson.version}`);
